src/app/app.module.ts
src/app/shelves/shelves.component.css
src/app/shelves/shelves.component.html
src/app/shelves/shelves.component.ts

This PR adds some very basic component scaffolding and logic to flesh out the shelves sidenav a little bit

Shelf sidenav

---

src/app/app-routing.module.ts
src/app/app.component.html
src/app/shelf-editor/shelf-editor.component.css
src/app/shelf-editor/shelf-editor.component.html
src/app/shelf-editor/shelf-editor.component.ts
src/app/shelves/shelves.component.css
src/app/shelves/shelves.component.html
src/app/shelves/shelves.component.ts

Shelves drawer

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/auth.service.ts
src/app/auth/auth.service.ts
src/app/auth/signin/signin.component.html
src/app/auth/signin/signin.component.scss
src/app/auth/signin/signin.component.ts
src/app/auth/signup/signup.component.html
src/app/auth/signup/signup.component.ts
src/app/header/header.component.html
src/app/header/header.component.ts
src/app/shared/auth.interceptor.ts
src/app/shared/shared.module.ts
src/app/user.ts

- Signin Component
- Signup Component
- Basic, unstyled login and signup forms
- HTTP Interceptor passes stored `auth-token` with every request (if != null).

Auth http interceptor

---

src/app/app.module.ts
src/app/auth/auth.service.ts
src/app/release/release-detail/release-detail.component.html
src/app/release/release-detail/release-detail.component.ts
src/app/release/release-notes/release-notes.component.html
src/app/release/release-notes/release-notes.component.scss
src/app/release/release-notes/release-notes.component.ts
src/app/shared/material/material.module.ts
src/app/shelf-add/shelf-add.component.html
src/app/shelf-add/shelf-add.component.scss
src/app/shelf-add/shelf-add.component.ts
src/app/shelf.service.ts
src/app/shelf.ts

Unauth warn

---

src/app/shelf.service.ts
src/app/shelf.ts

behind master b/c of merge commits

Shelves service

---

src/app/auth/auth.service.ts
src/app/auth/signup/signup.component.html
src/app/auth/signup/signup.component.ts
src/app/user.ts

- Removes the need to have a username on signup
- Updates NewUser and Users objects to reflect server-side equivalents

Username fix

---

package-lock.json
src/app/auth/auth.service.ts
src/app/auth/signup/signup.component.ts

Patches issue of inaccessible HttpResponse headers in login/signup due to stricter typing.  This solution will allow login/signup as normal, but does not necessarily handle errors in the best way. Not a high priority to change atm.

Auth updates

---

src/app/shelf-add/shelf-add.component.ts

Shelf edit date

---

src/app/shelf-add/shelf-add.component.ts
src/app/shelf.service.ts

Display snackbars to user on errors within ShelfAddComponent

Display shelf-add errors

---

src/app/release/release-detail/release-detail.component.ts
src/app/shelf-add/shelf-add.component.ts

On shelf add dialog, only show error snackbar if user is authenticated.

Detail snackbar fix

---

src/_app-theme.scss
src/app/search-results/_search-results-theme.scss
src/app/search-results/search-results.component.html
src/app/search-results/search-results.component.scss

Fallback images, margins, gutters.

Search styling

---

src/_app-theme.scss
src/app/release/release-detail/_release-detail-theme.scss
src/app/release/release-detail/release-detail.component.html
src/app/release/release-detail/release-detail.component.scss

Also set content to be alt tag and set default dimensions as 500x500

Display placeholder gradient if no img on detail

---

src/_app-theme.scss
src/app/routes.ts
src/app/shelves/shelf-detail/_shelf-detail-theme.scss
src/app/shelves/shelf-detail/shelf-detail.component.html
src/app/shelves/shelf-detail/shelf-detail.component.scss
src/app/shelves/shelf-detail/shelf-detail.component.ts
src/app/shelves/shelves-list.component.html
src/app/shelves/shelves.module.ts

Click on the 'more' tile to navigate to a mat-grid-list of all releases in that shelf.

Shelf detail

---

src/app/release/related-releases/related-releases.component.ts

Commented out b/c we may just want to modify it soon.

Remove fetching related releases on detail (due to server upds)

---

src/app/navbar/navbar.component.ts
src/app/routes.ts
src/app/search-results/search-results.component.ts

Search upds

---

src/app/release/release-detail/release-detail.component.ts
src/app/shelf-add/shelf-add.component.html
src/app/shelves/shelf-preview/shelf-preview.component.html
src/app/shelves/shelf-preview/shelf-preview.component.scss
src/app/shelves/shelf-preview/shelf-preview.component.ts

More changes to be made, but a start

Shelf preview styling

---

src/app/search-results/_search-results-theme.scss
src/app/search-results/search-results.component.html
src/app/search-results/search-results.component.scss
src/app/search-results/search-results.component.ts

Centers, updates message. To be refined.

No results style

---

src/app/shelves/shelf-detail/shelf-detail.component.html
src/app/shelves/shelves-list.component.html
src/app/shelves/shelves.module.ts

Oops this branch was named wrong because tired. Make each shelf one tile in shelf list instead of entire row

Shelf list

---

src/app/browse/artist-item.component.html
src/app/browse/artist.component.html
src/app/browse/label-item.component.html
src/app/browse/label.component.html
src/app/browse/release-item.component.html
src/app/release/release-notes/release-notes.component.html
src/app/search-results/result-group-list.html
src/app/shelf-add/shelf-add.component.html
src/app/shelves/shelf-detail/shelf-detail.component.html
src/app/shelves/shelf-preview/shelf-preview.component.html
src/app/shelves/shelves-list.component.html
src/styles/_general.scss

This actually doesn't work the way I thought it would, but committing to standardize syntax for onerrors

Fade in bars

---

src/app/shelves/shelf-preview/shelf-preview.component.html
src/app/shelves/shelf-preview/shelf-preview.component.scss

This is to be changed and built upon, but wanted to integrate my changes so that @johnlawsharrison can use them to edit on his dialog rampage. This does not address an empty image pushing the title over on the dialog

Shelf Preview background platform
